name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_NAME: brisk
  PROJECT_AUTHOR: "yair"
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin-${{ hashFiles('**/Cargo.lock') }}
      - name: Install cross
        run: |
            if ! [ -x "$(command -v cross)" ]; then
              cargo install cross
            fi

      - name: Build x86_64-unknown-linux-gnu
        run: cross build --target x86_64-unknown-linux-gnu --release

      - name: Build x86_64-pc-windows-gnu
        run: cross build --target x86_64-pc-windows-gnu --release

      - name: Rename binaries
        run: |
          mkdir -p brisk-bins
          ls -l target
          echo ${arch}
          ls -l target/*/release
          for arch in $(ls target); do
            if [[ -e "target/${arch}/release/brisk" ]]; then
              cp target/${arch}/release/brisk brisk-bins/brisk-${arch}
            fi
          done

      - name: Upload release binary
        uses: actions/upload-artifact@v4
        with:
          name: brisk-builds
          path: brisk-bins/
